apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-autoscaler
  template:
    metadata:
      labels:
        app: ai-autoscaler
    spec:
      containers:
      - name: autoscaler
        image: gcr.io/YOUR_PROJECT/ai-autoscaler:v1
        ports:
        - containerPort: 8080
